"""
Django settings for monerostack project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os 
# ── MCP server config ─────────────────────────────────────────────────────────
# django-mcp-server will import mcprpc.mcp and register toolsets at /mcp
MCP_SERVER = {
    "NAME": "monero-mcp",
    "DESCRIPTION": "Monero MCP bridge using Cake Wallet public nodes (no local daemon)",
    # If you add other tool modules, list them here (comma-separated string supported too)
    "TOOLS_MODULE": "mcprpc.mcp",
}

# ── Monero (Cake) region config ──────────────────────────────────────────────
# Region can be: "us", "eu", or "default" (global)
MONERO_REGION = os.getenv("MONERO_REGION", "us")

MONERO_NODES = {
    # All entries must be full JSON-RPC endpoints (end with /json_rpc)
    #"us":      "https://node3-us.monero.love:18081/json_rpc",
    #"eu":      "https://node2-eu.monero.love:18089/json_rpc",
    "cake":    "https://xmr-node.cakewallet.com:18081/json_rpc",
    #"singapore": "https://singapore.node.xmr.pm:18089/json_rpc",
    #"monerodevs1": "https://node.monerodevs.org:18089/json_rpc",
    #"monerodevs2": "https://node2.monerodevs.org:18089/json_rpc",
    #"monerodevs3": "https://node3.monerodevs.org:18089/json_rpc",
    "ravfx1":  "https://ravfx.its-a-node.org:18081/json_rpc",
    "ravfx2":  "https://ravfx2.its-a-node.org:18089/json_rpc",
    #"rucknium": "https://rucknium.me:18081/json_rpc",
    #"selsta1": "https://selsta1.featherwallet.net:18081/json_rpc",
    #"selsta2": "https://selsta2.featherwallet.net:18081/json_rpc",
    #"seth":    "https://node.sethforprivacy.com:18089/json_rpc",
    #"stormycloud": "https://xmr.stormycloud.org:18089/json_rpc",
    #"trocador": "https://node.trocador.app:18089/json_rpc",
    #"xmr.ru":  "https://node.xmr.ru:18081/json_rpc",
}

# Requests timeout for node calls
MONERO_RPC_TIMEOUT = int(os.getenv("MONERO_RPC_TIMEOUT", "20"))

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-06a+@q@hvu)v2p06bpet5f+%7ka18$n@_2xi9di2^*qm71*oct'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'mcprpc',
    'mcp_server'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'monerostack.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'monerostack.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
